# Use the official NGINX image as base
FROM ubuntu:latest

# Install Git, wget, and build tools
RUN apt-get update && \
    apt-get install -y git wget build-essential libpcre3 libpcre3-dev libssl-dev zlib1g zlib1g-dev && \
    rm -rf /var/lib/apt/lists/*

# Clone NGINX-RTMP module repository
RUN git clone https://github.com/arut/nginx-rtmp-module.git /nginx-rtmp-module && \
    rm -rf /nginx-rtmp-module/.git*

# Download NGINX source
RUN wget http://nginx.org/download/nginx-1.24.0.tar.gz && \
    tar -xf nginx-1.24.0.tar.gz && \
    rm nginx-1.24.0.tar.gz

# Build NGINX with RTMP module
RUN cd nginx-1.24.0 && \
    ./configure --with-http_ssl_module --add-module=../nginx-rtmp-module && \
    make && \
    make install

# Remove NGINX source and unnecessary packages
RUN rm -rf /nginx-1.24.0 /nginx-rtmp-module

# Copy your NGINX configuration file
COPY nginx.conf /usr/local/nginx/conf/nginx.conf

# Expose RTMP and HTTP ports
EXPOSE 1935
EXPOSE 8080

# Specify the full path to the NGINX binary in the CMD instruction
CMD ["/usr/local/nginx/sbin/nginx", "-g", "daemon off;"]

